### ISSUE TITLE
Publication of source code

### ISSUE THREAD

**Issue by threema-danilo** [jedisct1/rust-minisign-verify#3]
Hi, I just noticed that the version published on crates.io is 0.2.0 (https://crates.io/crates/minisign-verify) while the latest version here on GitHub is 0.1.8.

Do you plan to release the updated source code as well, or did I look at the wrong branch?

(PS: Thanks for this library, I'm currently creating a WASM wrapper so that it can be used from the browser as well. Let me know if this is something you're interested in!)

**Comment by jedisct1** [comment]
Yes! I just forgot to `git push` without `--tags`.

Done :)

**Comment by threema-danilo** [comment]
Great, thanks! 🙂

PS: An early version of the mentioned WASM lib is here: https://www.npmjs.com/package/@threema/wasm-minisign-verify
